org: josephcaba
service: api-alumnos-rds

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::944585571319:role/LabRole
  stage: ${opt:stage, 'dev'}     # Por defecto usa dev
  environment:
    DB_HOST: ${ssm:/rds_mysql_alumnos/punto_enlace~true}
    DB_NAME: ${sls:stage}
    DB_USER: user_${sls:stage}
    DB_PASSWORD: ${ssm:/rds_mysql_alumnos/user_${sls:stage}/password~true}

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    package:
      include:
        - ./** 
    events:
      - http:
          path: /alumnos/listar
          method: get
          cors: true
          integration: lambda
