org: josephcaba
service: api-alumnos-rds

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::944585571319:role/LabRole
  environment:
    DB_SECRET_NAME: rds_mysql_alumnos/user_${sls:stage}
    DB_USER: user_${sls:stage}
    DB_NAME: ${sls:stage}

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /alumnos/listar
          method: get
          cors: true
          integration: lambda

  rotarPasswords:
    handler: RotarPasswords.lambda_handler
    package:
      include:
        - ./**
    environment:
      DB_HOST_PARAM: /rds_mysql_alumnos/punto_enlace
      DB_ADMIN_USER: admin
      DB_ADMIN_PASSWORD_PARAM: /rds_mysql_alumnos/admin/password
    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: true
